version: 1.0.{build}

branches:
  only:
  - master

skip_tags: true

image: Ubuntu2204

cache:
  - linuxdeploy-x86_64.AppImage

install:
- sh: >-
    sudo dpkg --add-architecture i386

    sudo apt update

    dpkg-checkbuilddeps 2>&1 | sed 's/dpkg-checkbuilddeps:\serror:\sUnmet build dependencies: //g' | sed 's/[\(][^)]*[\)] //g' | sed 's/|//g' | xargs -n 1 sudo apt install -y

    sudo apt install --yes gcc-11 gcc-11-multilib g++-11 g++-11-multilib libc6-dev-i386 libx11-6:i386 libx11-dev:i386 libx11-xcb1:i386 libx11-xcb-dev:i386 libxcb-randr0-dev:i386 libasound2:i386 libasound2-dev:i386 libavutil56:i386 libavutil-dev:i386 libswresample3:i386 libswresample-dev:i386

    sudo ln -f -s /usr/bin/gcc-11 /usr/bin/gcc

    sudo ln -f -s /usr/bin/g++-11 /usr/bin/g++
    
    wget -nc https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    
    chmod +x linuxdeploy-x86_64.AppImage
    
    wget -nc https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage

    chmod +x linuxdeploy-plugin-qt-x86_64.AppImage
    
build_script:
- sh: sudo DEB_BUILD_OPTIONS=nostrip dpkg-buildpackage --no-sign -b
after_build:
- sh: sudo mv ../libtas*deb ./
- sh: for f in libtas*deb; do mv $f ${f/_amd/_${APPVEYOR_REPO_COMMIT:0:7}_amd}; done;
- sh: sudo ARCH=x86_64 NO_CLEANUP=1 ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run --appdir debian/libtas/ --plugin qt --output appimage
- sh: mv libTAS-x86_64.AppImage libtas_${APPVEYOR_REPO_COMMIT:0:7}_amd64.AppImage
artifacts:
- path: libtas*.deb
  name: libtas

- path: libtas-dbgsym*.ddeb
  name: libtas-dbgsym

- path: libtas*_amd64.AppImage
  name: libtas-appimage
